// Code generated by MockGen. DO NOT EDIT.
// Source: /home/wil/dev/sro/chat-service/pkg/service/chat.go
//
// Generated by this command:
//
//	mockgen -package=mocks -source=/home/wil/dev/sro/chat-service/pkg/service/chat.go -destination=/home/wil/dev/sro/chat-service/pkg/mocks/chat_mock.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	chat "github.com/ShatteredRealms/chat-service/pkg/model/chat"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockChatService is a mock of ChatService interface.
type MockChatService struct {
	ctrl     *gomock.Controller
	recorder *MockChatServiceMockRecorder
	isgomock struct{}
}

// MockChatServiceMockRecorder is the mock recorder for MockChatService.
type MockChatServiceMockRecorder struct {
	mock *MockChatService
}

// NewMockChatService creates a new mock instance.
func NewMockChatService(ctrl *gomock.Controller) *MockChatService {
	mock := &MockChatService{ctrl: ctrl}
	mock.recorder = &MockChatServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatService) EXPECT() *MockChatServiceMockRecorder {
	return m.recorder
}

// ReceiveChannelMessage mocks base method.
func (m *MockChatService) ReceiveChannelMessage(ctx context.Context, channelId *uuid.UUID, receiverCharacterId string) (*chat.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveChannelMessage", ctx, channelId, receiverCharacterId)
	ret0, _ := ret[0].(*chat.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReceiveChannelMessage indicates an expected call of ReceiveChannelMessage.
func (mr *MockChatServiceMockRecorder) ReceiveChannelMessage(ctx, channelId, receiverCharacterId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveChannelMessage", reflect.TypeOf((*MockChatService)(nil).ReceiveChannelMessage), ctx, channelId, receiverCharacterId)
}

// ReceiveDirectMessage mocks base method.
func (m *MockChatService) ReceiveDirectMessage(ctx context.Context, targetCharacterId, receiverCharacterId string) (*chat.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReceiveDirectMessage", ctx, targetCharacterId, receiverCharacterId)
	ret0, _ := ret[0].(*chat.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReceiveDirectMessage indicates an expected call of ReceiveDirectMessage.
func (mr *MockChatServiceMockRecorder) ReceiveDirectMessage(ctx, targetCharacterId, receiverCharacterId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveDirectMessage", reflect.TypeOf((*MockChatService)(nil).ReceiveDirectMessage), ctx, targetCharacterId, receiverCharacterId)
}

// SendChannelMessage mocks base method.
func (m *MockChatService) SendChannelMessage(ctx context.Context, channelId *uuid.UUID, msg *chat.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendChannelMessage", ctx, channelId, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendChannelMessage indicates an expected call of SendChannelMessage.
func (mr *MockChatServiceMockRecorder) SendChannelMessage(ctx, channelId, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendChannelMessage", reflect.TypeOf((*MockChatService)(nil).SendChannelMessage), ctx, channelId, msg)
}

// SendDirectMessage mocks base method.
func (m *MockChatService) SendDirectMessage(ctx context.Context, targetCharacterId string, msg *chat.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDirectMessage", ctx, targetCharacterId, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDirectMessage indicates an expected call of SendDirectMessage.
func (mr *MockChatServiceMockRecorder) SendDirectMessage(ctx, targetCharacterId, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDirectMessage", reflect.TypeOf((*MockChatService)(nil).SendDirectMessage), ctx, targetCharacterId, msg)
}
